//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogWork.AppResources.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LogWork.AppResources.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string alert_message_assigning {
            get {
                return ResourceManager.GetString("alert_message_assigning", resourceCulture);
            }
        }
        
        internal static string alert_message_assigning_intervention {
            get {
                return ResourceManager.GetString("alert_message_assigning_intervention", resourceCulture);
            }
        }
        
        internal static string alert_message_cancel {
            get {
                return ResourceManager.GetString("alert_message_cancel", resourceCulture);
            }
        }
        
        internal static string alert_message_delete_intervention_confirm {
            get {
                return ResourceManager.GetString("alert_message_delete_intervention_confirm", resourceCulture);
            }
        }
        
        internal static string alert_message_error {
            get {
                return ResourceManager.GetString("alert_message_error", resourceCulture);
            }
        }
        
        internal static string alert_message_intervention_already_assigned {
            get {
                return ResourceManager.GetString("alert_message_intervention_already_assigned", resourceCulture);
            }
        }
        
        internal static string alert_message_intervention_assigned {
            get {
                return ResourceManager.GetString("alert_message_intervention_assigned", resourceCulture);
            }
        }
        
        internal static string alert_message_log_out_confirm {
            get {
                return ResourceManager.GetString("alert_message_log_out_confirm", resourceCulture);
            }
        }
        
        internal static string alert_message_no {
            get {
                return ResourceManager.GetString("alert_message_no", resourceCulture);
            }
        }
        
        internal static string alert_message_ok {
            get {
                return ResourceManager.GetString("alert_message_ok", resourceCulture);
            }
        }
        
        internal static string alert_message_sync_completed {
            get {
                return ResourceManager.GetString("alert_message_sync_completed", resourceCulture);
            }
        }
        
        internal static string alert_message_sync_failed {
            get {
                return ResourceManager.GetString("alert_message_sync_failed", resourceCulture);
            }
        }
        
        internal static string alert_message_try_again {
            get {
                return ResourceManager.GetString("alert_message_try_again", resourceCulture);
            }
        }
        
        internal static string alert_message_wrong_user_credentials {
            get {
                return ResourceManager.GetString("alert_message_wrong_user_credentials", resourceCulture);
            }
        }
        
        internal static string alert_message_yes {
            get {
                return ResourceManager.GetString("alert_message_yes", resourceCulture);
            }
        }
        
        internal static string alert_title_authentication_fail {
            get {
                return ResourceManager.GetString("alert_title_authentication_fail", resourceCulture);
            }
        }
        
        internal static string alert_title_error {
            get {
                return ResourceManager.GetString("alert_title_error", resourceCulture);
            }
        }
        
        internal static string alert_title_intervention {
            get {
                return ResourceManager.GetString("alert_title_intervention", resourceCulture);
            }
        }
        
        internal static string alert_title_log_in {
            get {
                return ResourceManager.GetString("alert_title_log_in", resourceCulture);
            }
        }
        
        internal static string alert_title_log_out {
            get {
                return ResourceManager.GetString("alert_title_log_out", resourceCulture);
            }
        }
        
        internal static string alert_title_server_error {
            get {
                return ResourceManager.GetString("alert_title_server_error", resourceCulture);
            }
        }
        
        internal static string button_text_add_an_intervention {
            get {
                return ResourceManager.GetString("button_text_add_an_intervention", resourceCulture);
            }
        }
        
        internal static string button_text_add_an_quote {
            get {
                return ResourceManager.GetString("button_text_add_an_quote", resourceCulture);
            }
        }
        
        internal static string button_text_assign_to_me {
            get {
                return ResourceManager.GetString("button_text_assign_to_me", resourceCulture);
            }
        }
        
        internal static string button_text_cancel {
            get {
                return ResourceManager.GetString("button_text_cancel", resourceCulture);
            }
        }
        
        internal static string button_text_open_map {
            get {
                return ResourceManager.GetString("button_text_open_map", resourceCulture);
            }
        }
        
        internal static string button_text_reset {
            get {
                return ResourceManager.GetString("button_text_reset", resourceCulture);
            }
        }
        
        internal static string button_text_save {
            get {
                return ResourceManager.GetString("button_text_save", resourceCulture);
            }
        }
        
        internal static string button_text_send_email {
            get {
                return ResourceManager.GetString("button_text_send_email", resourceCulture);
            }
        }
        
        internal static string button_text_sign_in {
            get {
                return ResourceManager.GetString("button_text_sign_in", resourceCulture);
            }
        }
        
        internal static string completed {
            get {
                return ResourceManager.GetString("completed", resourceCulture);
            }
        }
        
        internal static string content_message_synchronizing {
            get {
                return ResourceManager.GetString("content_message_synchronizing", resourceCulture);
            }
        }
        
        internal static string entry_hint_account {
            get {
                return ResourceManager.GetString("entry_hint_account", resourceCulture);
            }
        }
        
        internal static string entry_hint_adresse {
            get {
                return ResourceManager.GetString("entry_hint_adresse", resourceCulture);
            }
        }
        
        internal static string entry_hint_client {
            get {
                return ResourceManager.GetString("entry_hint_client", resourceCulture);
            }
        }
        
        internal static string entry_hint_contract {
            get {
                return ResourceManager.GetString("entry_hint_contract", resourceCulture);
            }
        }
        
        internal static string page_title_search_contract {
            get {
                return ResourceManager.GetString("page_title_search_contract", resourceCulture);
            }
        }
        
        internal static string entry_hint_password {
            get {
                return ResourceManager.GetString("entry_hint_password", resourceCulture);
            }
        }
        
        internal static string entry_hint_search {
            get {
                return ResourceManager.GetString("entry_hint_search", resourceCulture);
            }
        }
        
        internal static string entry_hint_title {
            get {
                return ResourceManager.GetString("entry_hint_title", resourceCulture);
            }
        }
        
        internal static string entry_hint_user_name {
            get {
                return ResourceManager.GetString("entry_hint_user_name", resourceCulture);
            }
        }
        
        internal static string error_fulfill_login {
            get {
                return ResourceManager.GetString("error_fulfill_login", resourceCulture);
            }
        }
        
        internal static string home_menu_title_about {
            get {
                return ResourceManager.GetString("home_menu_title_about", resourceCulture);
            }
        }
        
        internal static string home_menu_title_addresses {
            get {
                return ResourceManager.GetString("home_menu_title_addresses", resourceCulture);
            }
        }
        
        internal static string home_menu_title_customers {
            get {
                return ResourceManager.GetString("home_menu_title_customers", resourceCulture);
            }
        }
        
        internal static string home_menu_title_interventions {
            get {
                return ResourceManager.GetString("home_menu_title_interventions", resourceCulture);
            }
        }
        
        internal static string home_menu_title_interventions_not_assigned {
            get {
                return ResourceManager.GetString("home_menu_title_interventions_not_assigned", resourceCulture);
            }
        }
        
        internal static string home_menu_title_log_out {
            get {
                return ResourceManager.GetString("home_menu_title_log_out", resourceCulture);
            }
        }
        
        internal static string home_menu_title_messages {
            get {
                return ResourceManager.GetString("home_menu_title_messages", resourceCulture);
            }
        }
        
        internal static string home_menu_title_settings {
            get {
                return ResourceManager.GetString("home_menu_title_settings", resourceCulture);
            }
        }
        
        internal static string home_menu_title_tracking {
            get {
                return ResourceManager.GetString("home_menu_title_tracking", resourceCulture);
            }
        }
        
        internal static string home_menu_title_quote {
            get {
                return ResourceManager.GetString("home_menu_title_quote", resourceCulture);
            }
        }
        
        internal static string home_menu_title_invoice {
            get {
                return ResourceManager.GetString("home_menu_title_invoice", resourceCulture);
            }
        }
        
        internal static string intervention_status_completed {
            get {
                return ResourceManager.GetString("intervention_status_completed", resourceCulture);
            }
        }
        
        internal static string intervention_status_in_progress {
            get {
                return ResourceManager.GetString("intervention_status_in_progress", resourceCulture);
            }
        }
        
        internal static string in_progress {
            get {
                return ResourceManager.GetString("in_progress", resourceCulture);
            }
        }
        
        internal static string label_text_contract {
            get {
                return ResourceManager.GetString("label_text_contract", resourceCulture);
            }
        }
        
        internal static string label_text_action {
            get {
                return ResourceManager.GetString("label_text_action", resourceCulture);
            }
        }
        
        internal static string label_text_actions {
            get {
                return ResourceManager.GetString("label_text_actions", resourceCulture);
            }
        }
        
        internal static string label_text_address {
            get {
                return ResourceManager.GetString("label_text_address", resourceCulture);
            }
        }
        
        internal static string label_text_attachments {
            get {
                return ResourceManager.GetString("label_text_attachments", resourceCulture);
            }
        }
        
        internal static string label_text_begin {
            get {
                return ResourceManager.GetString("label_text_begin", resourceCulture);
            }
        }
        
        internal static string label_text_cancel {
            get {
                return ResourceManager.GetString("label_text_cancel", resourceCulture);
            }
        }
        
        internal static string label_text_client {
            get {
                return ResourceManager.GetString("label_text_client", resourceCulture);
            }
        }
        
        internal static string label_text_comment {
            get {
                return ResourceManager.GetString("label_text_comment", resourceCulture);
            }
        }
        
        internal static string label_text_private_comment {
            get {
                return ResourceManager.GetString("label_text_private_comment", resourceCulture);
            }
        }
        
        internal static string label_text_public_comment {
            get {
                return ResourceManager.GetString("label_text_public_comment", resourceCulture);
            }
        }
        
        internal static string label_text_completed {
            get {
                return ResourceManager.GetString("label_text_completed", resourceCulture);
            }
        }
        
        internal static string label_text_done {
            get {
                return ResourceManager.GetString("label_text_done", resourceCulture);
            }
        }
        
        internal static string label_text_email {
            get {
                return ResourceManager.GetString("label_text_email", resourceCulture);
            }
        }
        
        internal static string label_text_end {
            get {
                return ResourceManager.GetString("label_text_end", resourceCulture);
            }
        }
        
        internal static string label_text_fax {
            get {
                return ResourceManager.GetString("label_text_fax", resourceCulture);
            }
        }
        
        internal static string label_text_files {
            get {
                return ResourceManager.GetString("label_text_files", resourceCulture);
            }
        }
        
        internal static string label_text_filiale {
            get {
                return ResourceManager.GetString("label_text_filiale", resourceCulture);
            }
        }
        
        internal static string label_text_full_name {
            get {
                return ResourceManager.GetString("label_text_full_name", resourceCulture);
            }
        }
        
        internal static string label_text_further_info {
            get {
                return ResourceManager.GetString("label_text_further_info", resourceCulture);
            }
        }
        
        internal static string label_text_history {
            get {
                return ResourceManager.GetString("label_text_history", resourceCulture);
            }
        }
        
        internal static string label_text_hours {
            get {
                return ResourceManager.GetString("label_text_hours", resourceCulture);
            }
        }
        
        internal static string label_text_in_progress {
            get {
                return ResourceManager.GetString("label_text_in_progress", resourceCulture);
            }
        }
        
        internal static string label_text_media {
            get {
                return ResourceManager.GetString("label_text_media", resourceCulture);
            }
        }
        
        internal static string label_text_phone {
            get {
                return ResourceManager.GetString("label_text_phone", resourceCulture);
            }
        }
        
        internal static string label_text_pick_photo {
            get {
                return ResourceManager.GetString("label_text_pick_photo", resourceCulture);
            }
        }
        
        internal static string label_text_planned {
            get {
                return ResourceManager.GetString("label_text_planned", resourceCulture);
            }
        }
        
        internal static string label_text_products {
            get {
                return ResourceManager.GetString("label_text_products", resourceCulture);
            }
        }
        
        internal static string label_text_signature {
            get {
                return ResourceManager.GetString("label_text_signature", resourceCulture);
            }
        }
        
        internal static string label_text_societe {
            get {
                return ResourceManager.GetString("label_text_societe", resourceCulture);
            }
        }
        
        internal static string label_text_take_photo {
            get {
                return ResourceManager.GetString("label_text_take_photo", resourceCulture);
            }
        }
        
        internal static string label_text_title {
            get {
                return ResourceManager.GetString("label_text_title", resourceCulture);
            }
        }
        
        internal static string label_text_working_time {
            get {
                return ResourceManager.GetString("label_text_working_time", resourceCulture);
            }
        }
        
        internal static string page_title_about {
            get {
                return ResourceManager.GetString("page_title_about", resourceCulture);
            }
        }
        
        internal static string page_title_addresses {
            get {
                return ResourceManager.GetString("page_title_addresses", resourceCulture);
            }
        }
        
        internal static string page_title_customers {
            get {
                return ResourceManager.GetString("page_title_customers", resourceCulture);
            }
        }
        
        internal static string page_title_edit_intervention {
            get {
                return ResourceManager.GetString("page_title_edit_intervention", resourceCulture);
            }
        }
        
        internal static string page_title_interventions {
            get {
                return ResourceManager.GetString("page_title_interventions", resourceCulture);
            }
        }
        
        internal static string page_title_interventions_not_assigned {
            get {
                return ResourceManager.GetString("page_title_interventions_not_assigned", resourceCulture);
            }
        }
        
        internal static string page_title_login {
            get {
                return ResourceManager.GetString("page_title_login", resourceCulture);
            }
        }
        
        internal static string page_title_messages {
            get {
                return ResourceManager.GetString("page_title_messages", resourceCulture);
            }
        }
        
        internal static string page_title_new_intervention {
            get {
                return ResourceManager.GetString("page_title_new_intervention", resourceCulture);
            }
        }
        
        internal static string page_title_new_quote {
            get {
                return ResourceManager.GetString("page_title_new_quote", resourceCulture);
            }
        }
        
        internal static string page_title_search_address {
            get {
                return ResourceManager.GetString("page_title_search_address", resourceCulture);
            }
        }
        
        internal static string page_title_search_client {
            get {
                return ResourceManager.GetString("page_title_search_client", resourceCulture);
            }
        }
        
        internal static string page_title_settings {
            get {
                return ResourceManager.GetString("page_title_settings", resourceCulture);
            }
        }
        
        internal static string page_title_signature {
            get {
                return ResourceManager.GetString("page_title_signature", resourceCulture);
            }
        }
        
        internal static string page_title_tracking {
            get {
                return ResourceManager.GetString("page_title_tracking", resourceCulture);
            }
        }
        
        internal static string picker_title_select {
            get {
                return ResourceManager.GetString("picker_title_select", resourceCulture);
            }
        }
        
        internal static string button_text_history {
            get {
                return ResourceManager.GetString("button_text_history", resourceCulture);
            }
        }
        
        internal static string label_text_further_infomations {
            get {
                return ResourceManager.GetString("label_text_further_infomations", resourceCulture);
            }
        }
        
        internal static string page_title_histoty {
            get {
                return ResourceManager.GetString("page_title_histoty", resourceCulture);
            }
        }
        
        internal static string label_text_date {
            get {
                return ResourceManager.GetString("label_text_date", resourceCulture);
            }
        }
        
        internal static string alert_message_get_history {
            get {
                return ResourceManager.GetString("alert_message_get_history", resourceCulture);
            }
        }
        
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        internal static string label_text_dates {
            get {
                return ResourceManager.GetString("label_text_dates", resourceCulture);
            }
        }
        
        internal static string label_text_due_date {
            get {
                return ResourceManager.GetString("label_text_due_date", resourceCulture);
            }
        }
        
        internal static string label_text_reference {
            get {
                return ResourceManager.GetString("label_text_reference", resourceCulture);
            }
        }
        
        internal static string alert_message_send_mail_successed {
            get {
                return ResourceManager.GetString("alert_message_send_mail_successed", resourceCulture);
            }
        }
        
        internal static string loading_text_loggin {
            get {
                return ResourceManager.GetString("loading_text_loggin", resourceCulture);
            }
        }
        
        internal static string alert_message_cant_send_email {
            get {
                return ResourceManager.GetString("alert_message_cant_send_email", resourceCulture);
            }
        }
        
        internal static string alert_message_bad_connection {
            get {
                return ResourceManager.GetString("alert_message_bad_connection", resourceCulture);
            }
        }
        
        internal static string alert_message_server_error {
            get {
                return ResourceManager.GetString("alert_message_server_error", resourceCulture);
            }
        }
        
        internal static string button_text_delete {
            get {
                return ResourceManager.GetString("button_text_delete", resourceCulture);
            }
        }
        
        internal static string alert_message_intervention_no_client {
            get {
                return ResourceManager.GetString("alert_message_intervention_no_client", resourceCulture);
            }
        }
        
        internal static string search_hint_input_customer {
            get {
                return ResourceManager.GetString("search_hint_input_customer", resourceCulture);
            }
        }
        
        internal static string button_text_add_new_customer {
            get {
                return ResourceManager.GetString("button_text_add_new_customer", resourceCulture);
            }
        }
        
        internal static string label_text_addresses {
            get {
                return ResourceManager.GetString("label_text_addresses", resourceCulture);
            }
        }
        
        internal static string label_text_city {
            get {
                return ResourceManager.GetString("label_text_city", resourceCulture);
            }
        }
        
        internal static string label_text_postal_code {
            get {
                return ResourceManager.GetString("label_text_postal_code", resourceCulture);
            }
        }
        
        internal static string label_text_street {
            get {
                return ResourceManager.GetString("label_text_street", resourceCulture);
            }
        }
        
        internal static string label_text_interventions {
            get {
                return ResourceManager.GetString("label_text_interventions", resourceCulture);
            }
        }
        
        internal static string label_text_infomations {
            get {
                return ResourceManager.GetString("label_text_infomations", resourceCulture);
            }
        }
        
        internal static string label_text_status {
            get {
                return ResourceManager.GetString("label_text_status", resourceCulture);
            }
        }
        
        internal static string button_text_add_new_address {
            get {
                return ResourceManager.GetString("button_text_add_new_address", resourceCulture);
            }
        }
        
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        internal static string label_text_customers {
            get {
                return ResourceManager.GetString("label_text_customers", resourceCulture);
            }
        }
        
        internal static string label_text_latitude {
            get {
                return ResourceManager.GetString("label_text_latitude", resourceCulture);
            }
        }
        
        internal static string label_text_longitude {
            get {
                return ResourceManager.GetString("label_text_longitude", resourceCulture);
            }
        }
        
        internal static string search_hint_input_address {
            get {
                return ResourceManager.GetString("search_hint_input_address", resourceCulture);
            }
        }
        
        internal static string label_text_view {
            get {
                return ResourceManager.GetString("label_text_view", resourceCulture);
            }
        }
        
        internal static string text_cancel {
            get {
                return ResourceManager.GetString("text_cancel", resourceCulture);
            }
        }
        
        internal static string page_title_edit_customer {
            get {
                return ResourceManager.GetString("page_title_edit_customer", resourceCulture);
            }
        }
        
        internal static string page_title_new_customer {
            get {
                return ResourceManager.GetString("page_title_new_customer", resourceCulture);
            }
        }
        
        internal static string entry_hint_comment {
            get {
                return ResourceManager.GetString("entry_hint_comment", resourceCulture);
            }
        }
        
        internal static string entry_hint_email {
            get {
                return ResourceManager.GetString("entry_hint_email", resourceCulture);
            }
        }
        
        internal static string entry_hint_fax {
            get {
                return ResourceManager.GetString("entry_hint_fax", resourceCulture);
            }
        }
        
        internal static string entry_hint_nom {
            get {
                return ResourceManager.GetString("entry_hint_nom", resourceCulture);
            }
        }
        
        internal static string entry_hint_phone {
            get {
                return ResourceManager.GetString("entry_hint_phone", resourceCulture);
            }
        }
        
        internal static string entry_hint_prenom {
            get {
                return ResourceManager.GetString("entry_hint_prenom", resourceCulture);
            }
        }
        
        internal static string entry_hint_societe {
            get {
                return ResourceManager.GetString("entry_hint_societe", resourceCulture);
            }
        }
        
        internal static string page_title_new_address {
            get {
                return ResourceManager.GetString("page_title_new_address", resourceCulture);
            }
        }
        
        internal static string entry_hint_address {
            get {
                return ResourceManager.GetString("entry_hint_address", resourceCulture);
            }
        }
        
        internal static string entry_hint_code_postal {
            get {
                return ResourceManager.GetString("entry_hint_code_postal", resourceCulture);
            }
        }
        
        internal static string entry_hint_code_ville {
            get {
                return ResourceManager.GetString("entry_hint_code_ville", resourceCulture);
            }
        }
        
        internal static string page_title_new_message {
            get {
                return ResourceManager.GetString("page_title_new_message", resourceCulture);
            }
        }
        
        internal static string label_text_to_2 {
            get {
                return ResourceManager.GetString("label_text_to_2", resourceCulture);
            }
        }
        
        internal static string label_text_title_2 {
            get {
                return ResourceManager.GetString("label_text_title_2", resourceCulture);
            }
        }
        
        internal static string page_title_search_user {
            get {
                return ResourceManager.GetString("page_title_search_user", resourceCulture);
            }
        }
        
        internal static string label_text_to {
            get {
                return ResourceManager.GetString("label_text_to", resourceCulture);
            }
        }
        
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        internal static string label_text_send_mail {
            get {
                return ResourceManager.GetString("label_text_send_mail", resourceCulture);
            }
        }
        
        internal static string MOBILE_CAN_EDIT_CLIENT_ADRESSE {
            get {
                return ResourceManager.GetString("MOBILE_CAN_EDIT_CLIENT_ADRESSE", resourceCulture);
            }
        }
        
        internal static string MOBILE_CAN_EDIT_DATES {
            get {
                return ResourceManager.GetString("MOBILE_CAN_EDIT_DATES", resourceCulture);
            }
        }
        
        internal static string MOBILE_CAN_EDIT_HOURS {
            get {
                return ResourceManager.GetString("MOBILE_CAN_EDIT_HOURS", resourceCulture);
            }
        }
        
        internal static string MOBILE_CAN_EDIT_USERS {
            get {
                return ResourceManager.GetString("MOBILE_CAN_EDIT_USERS", resourceCulture);
            }
        }
        
        internal static string MOBILE_CAN_SEARCH_PRODUCT {
            get {
                return ResourceManager.GetString("MOBILE_CAN_SEARCH_PRODUCT", resourceCulture);
            }
        }
        
        internal static string MOBILE_ACTIVATE_SEARCH_PHOTO {
            get {
                return ResourceManager.GetString("MOBILE_ACTIVATE_SEARCH_PHOTO", resourceCulture);
            }
        }
        
        internal static string MOBILE_ACTIVATE_TAKE_PHOTO {
            get {
                return ResourceManager.GetString("MOBILE_ACTIVATE_TAKE_PHOTO", resourceCulture);
            }
        }
        
        internal static string MOBILE_ACTIVATE_TAKE_SIGNATURE {
            get {
                return ResourceManager.GetString("MOBILE_ACTIVATE_TAKE_SIGNATURE", resourceCulture);
            }
        }
        
        internal static string MOBILE_DISPLAY_CHRONO {
            get {
                return ResourceManager.GetString("MOBILE_DISPLAY_CHRONO", resourceCulture);
            }
        }
        
        internal static string MOBILE_DISPLAY_FIELD_TITLE {
            get {
                return ResourceManager.GetString("MOBILE_DISPLAY_FIELD_TITLE", resourceCulture);
            }
        }
        
        internal static string MOBILE_DISPLAY_HOME_INTERVENTION_ADRESSE {
            get {
                return ResourceManager.GetString("MOBILE_DISPLAY_HOME_INTERVENTION_ADRESSE", resourceCulture);
            }
        }
        
        internal static string MOBILE_DISPLAY_HOME_INTERVENTION_CLIENT {
            get {
                return ResourceManager.GetString("MOBILE_DISPLAY_HOME_INTERVENTION_CLIENT", resourceCulture);
            }
        }
        
        internal static string MOBILE_DISPLAY_HOME_INTERVENTION_PRIORITY {
            get {
                return ResourceManager.GetString("MOBILE_DISPLAY_HOME_INTERVENTION_PRIORITY", resourceCulture);
            }
        }
        
        internal static string MOBILE_DISPLAY_HOME_INTERVENTION_TITLE {
            get {
                return ResourceManager.GetString("MOBILE_DISPLAY_HOME_INTERVENTION_TITLE", resourceCulture);
            }
        }
        
        internal static string MOBILE_DISPLAY_HOME_INTERVENTION_TOGGLE_PROGRESS {
            get {
                return ResourceManager.GetString("MOBILE_DISPLAY_HOME_INTERVENTION_TOGGLE_PROGRESS", resourceCulture);
            }
        }
        
        internal static string MOBILE_DISPLAY_MAP {
            get {
                return ResourceManager.GetString("MOBILE_DISPLAY_MAP", resourceCulture);
            }
        }
        
        internal static string MOBILE_ENABLE_PRODUCT {
            get {
                return ResourceManager.GetString("MOBILE_ENABLE_PRODUCT", resourceCulture);
            }
        }
        
        internal static string APP_FONT_SIZE {
            get {
                return ResourceManager.GetString("APP_FONT_SIZE", resourceCulture);
            }
        }
        
        internal static string MOBILE_HOUR_START_DEFAULT {
            get {
                return ResourceManager.GetString("MOBILE_HOUR_START_DEFAULT", resourceCulture);
            }
        }
        
        internal static string MOBILE_HOUR_START_ENABLE {
            get {
                return ResourceManager.GetString("MOBILE_HOUR_START_ENABLE", resourceCulture);
            }
        }
        
        internal static string APP_LAST_SYNCHRO {
            get {
                return ResourceManager.GetString("APP_LAST_SYNCHRO", resourceCulture);
            }
        }
        
        internal static string APP_LAST_SYNCHRO_PRODUCT {
            get {
                return ResourceManager.GetString("APP_LAST_SYNCHRO_PRODUCT", resourceCulture);
            }
        }
        
        internal static string APP_MEDIA_SIZE_MAX {
            get {
                return ResourceManager.GetString("APP_MEDIA_SIZE_MAX", resourceCulture);
            }
        }
        
        internal static string MOBILE_NOTIF_INTERVENTION {
            get {
                return ResourceManager.GetString("MOBILE_NOTIF_INTERVENTION", resourceCulture);
            }
        }
        
        internal static string MOBILE_NOTIF_MESSAGE {
            get {
                return ResourceManager.GetString("MOBILE_NOTIF_MESSAGE", resourceCulture);
            }
        }
        
        internal static string APP_PURGE_DATA {
            get {
                return ResourceManager.GetString("APP_PURGE_DATA", resourceCulture);
            }
        }
        
        internal static string MOBILE_REPORTER_INTERVENTIONS_DEFAULT {
            get {
                return ResourceManager.GetString("MOBILE_REPORTER_INTERVENTIONS_DEFAULT", resourceCulture);
            }
        }
        
        internal static string MOBILE_SEND_MAIL {
            get {
                return ResourceManager.GetString("MOBILE_SEND_MAIL", resourceCulture);
            }
        }
        
        internal static string APP_LANGUAGE {
            get {
                return ResourceManager.GetString("APP_LANGUAGE", resourceCulture);
            }
        }
        
        internal static string CATEGORY_HOURS_WORKED {
            get {
                return ResourceManager.GetString("CATEGORY_HOURS_WORKED", resourceCulture);
            }
        }
        
        internal static string CATEGORY_LANGUAGES {
            get {
                return ResourceManager.GetString("CATEGORY_LANGUAGES", resourceCulture);
            }
        }
        
        internal static string CATEGORY_LIST_OF_INTERVENTIONS {
            get {
                return ResourceManager.GetString("CATEGORY_LIST_OF_INTERVENTIONS", resourceCulture);
            }
        }
        
        internal static string CATEGORY_MODIFY_AN_INTERVENTION {
            get {
                return ResourceManager.GetString("CATEGORY_MODIFY_AN_INTERVENTION", resourceCulture);
            }
        }
        
        internal static string CATEGORY_NOTIFICATIONS {
            get {
                return ResourceManager.GetString("CATEGORY_NOTIFICATIONS", resourceCulture);
            }
        }
        
        internal static string CATEGORY_SYNCHRONIZATION {
            get {
                return ResourceManager.GetString("CATEGORY_SYNCHRONIZATION", resourceCulture);
            }
        }
        
        internal static string CATEGORY_VIEW_INTERVENTIONS {
            get {
                return ResourceManager.GetString("CATEGORY_VIEW_INTERVENTIONS", resourceCulture);
            }
        }
        
        internal static string CATEGORY_VISUAL {
            get {
                return ResourceManager.GetString("CATEGORY_VISUAL", resourceCulture);
            }
        }
        
        internal static string CATEGORY_NO_CATEGORY {
            get {
                return ResourceManager.GetString("CATEGORY_NO_CATEGORY", resourceCulture);
            }
        }
        
        internal static string label_text_send_mail_2 {
            get {
                return ResourceManager.GetString("label_text_send_mail_2", resourceCulture);
            }
        }
        
        internal static string label_text_users {
            get {
                return ResourceManager.GetString("label_text_users", resourceCulture);
            }
        }
        
        internal static string label_text_actions_2 {
            get {
                return ResourceManager.GetString("label_text_actions_2", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_APP_LANGUAGE {
            get {
                return ResourceManager.GetString("DESCRIPTION_APP_LANGUAGE", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_APP_LAST_SYNCHRO {
            get {
                return ResourceManager.GetString("DESCRIPTION_APP_LAST_SYNCHRO", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_APP_LAST_SYNCHRO_PRODUCT {
            get {
                return ResourceManager.GetString("DESCRIPTION_APP_LAST_SYNCHRO_PRODUCT", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_ACTIVATE_SEARCH_PHOTO {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_ACTIVATE_SEARCH_PHOTO", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_ACTIVATE_TAKE_PHOTO {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_ACTIVATE_TAKE_PHOTO", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_ACTIVATE_TAKE_SIGNATURE {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_ACTIVATE_TAKE_SIGNATURE", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_CAN_EDIT_CLIENT_ADDRESS {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_CAN_EDIT_CLIENT_ADDRESS", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_CAN_EDIT_DATES {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_CAN_EDIT_DATES", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_CAN_EDIT_HOURS {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_CAN_EDIT_HOURS", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_CAN_EDIT_USERS {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_CAN_EDIT_USERS", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_CAN_SEARCH_PRODUCT {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_CAN_SEARCH_PRODUCT", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_DISPLAY_CHRONO {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_DISPLAY_CHRONO", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_DISPLAY_FIELD_TITLE {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_DISPLAY_FIELD_TITLE", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_DISPLAY_HOME_INTERVENTION_ADDRESS {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_DISPLAY_HOME_INTERVENTION_ADDRESS", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_DISPLAY_HOME_INTERVENTION_CLIENT {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_DISPLAY_HOME_INTERVENTION_CLIENT", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_DISPLAY_HOME_INTERVENTION_PRIORITY {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_DISPLAY_HOME_INTERVENTION_PRIORITY", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_DISPLAY_HOME_INTERVENTION_TITLE {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_DISPLAY_HOME_INTERVENTION_TITLE", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_DISPLAY_HOME_INTERVENTION_TOGGLE_PROGRESS {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_DISPLAY_HOME_INTERVENTION_TOGGLE_PROGRESS", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_DISPLAY_MAP {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_DISPLAY_MAP", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_ENABLE_PRODUCT {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_ENABLE_PRODUCT", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_HOUR_START_DEFAULT {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_HOUR_START_DEFAULT", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_HOUR_START_ENABLE {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_HOUR_START_ENABLE", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_NOTIF_INTERVENTION {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_NOTIF_INTERVENTION", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_NOTIF_MESSAGE {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_NOTIF_MESSAGE", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_REPORTER_INTERVENTIONS {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_REPORTER_INTERVENTIONS", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_SEND_MAIL {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_SEND_MAIL", resourceCulture);
            }
        }
        
        internal static string APP_RESET_DATA {
            get {
                return ResourceManager.GetString("APP_RESET_DATA", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_APP_RESET_DATA {
            get {
                return ResourceManager.GetString("DESCRIPTION_APP_RESET_DATA", resourceCulture);
            }
        }
        
        internal static string MESSAGE_APP_LAST_SYNCHRO {
            get {
                return ResourceManager.GetString("MESSAGE_APP_LAST_SYNCHRO", resourceCulture);
            }
        }
        
        internal static string MESSAGE_APP_LAST_SYNCHRO_PRODUCT {
            get {
                return ResourceManager.GetString("MESSAGE_APP_LAST_SYNCHRO_PRODUCT", resourceCulture);
            }
        }
        
        internal static string MESSAGE_APP_RESET_DATA {
            get {
                return ResourceManager.GetString("MESSAGE_APP_RESET_DATA", resourceCulture);
            }
        }
        
        internal static string label_text_current_value_2 {
            get {
                return ResourceManager.GetString("label_text_current_value_2", resourceCulture);
            }
        }
        
        internal static string alert_message_intervention_no_address {
            get {
                return ResourceManager.GetString("alert_message_intervention_no_address", resourceCulture);
            }
        }
        
        internal static string page_title_search_product {
            get {
                return ResourceManager.GetString("page_title_search_product", resourceCulture);
            }
        }
        
        internal static string label_text_add_product {
            get {
                return ResourceManager.GetString("label_text_add_product", resourceCulture);
            }
        }
        
        internal static string alert_message_intervention_assign_error {
            get {
                return ResourceManager.GetString("alert_message_intervention_assign_error", resourceCulture);
            }
        }
        
        internal static string alert_message_get_location_error {
            get {
                return ResourceManager.GetString("alert_message_get_location_error", resourceCulture);
            }
        }
        
        internal static string en_US {
            get {
                return ResourceManager.GetString("en_US", resourceCulture);
            }
        }
        
        internal static string fr_FR {
            get {
                return ResourceManager.GetString("fr_FR", resourceCulture);
            }
        }
        
        internal static string page_title_intervention_detail {
            get {
                return ResourceManager.GetString("page_title_intervention_detail", resourceCulture);
            }
        }
        
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        internal static string label_text_mins {
            get {
                return ResourceManager.GetString("label_text_mins", resourceCulture);
            }
        }
        
        internal static string label_text_detail {
            get {
                return ResourceManager.GetString("label_text_detail", resourceCulture);
            }
        }
        
        internal static string label_text_camera {
            get {
                return ResourceManager.GetString("label_text_camera", resourceCulture);
            }
        }
        
        internal static string label_text_library {
            get {
                return ResourceManager.GetString("label_text_library", resourceCulture);
            }
        }
        
        internal static string APP_LAST_SYNCHRO_INVOICE {
            get {
                return ResourceManager.GetString("APP_LAST_SYNCHRO_INVOICE", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_APP_LAST_SYNCHRO_INVOICE {
            get {
                return ResourceManager.GetString("DESCRIPTION_APP_LAST_SYNCHRO_INVOICE", resourceCulture);
            }
        }
        
        internal static string MESSAGE_APP_LAST_SYNCHRO_INVOICE {
            get {
                return ResourceManager.GetString("MESSAGE_APP_LAST_SYNCHRO_INVOICE", resourceCulture);
            }
        }
        
        internal static string page_title_invoices {
            get {
                return ResourceManager.GetString("page_title_invoices", resourceCulture);
            }
        }
        
        internal static string search_hint_search {
            get {
                return ResourceManager.GetString("search_hint_search", resourceCulture);
            }
        }
        
        internal static string page_title_invoice_detail {
            get {
                return ResourceManager.GetString("page_title_invoice_detail", resourceCulture);
            }
        }
        
        internal static string page_title_quotes {
            get {
                return ResourceManager.GetString("page_title_quotes", resourceCulture);
            }
        }
        
        internal static string page_title_add_a_product {
            get {
                return ResourceManager.GetString("page_title_add_a_product", resourceCulture);
            }
        }
        
        internal static string button_text_add_product {
            get {
                return ResourceManager.GetString("button_text_add_product", resourceCulture);
            }
        }
        
        internal static string label_text_name {
            get {
                return ResourceManager.GetString("label_text_name", resourceCulture);
            }
        }
        
        internal static string label_text_price_without_tax {
            get {
                return ResourceManager.GetString("label_text_price_without_tax", resourceCulture);
            }
        }
        
        internal static string label_text_quantity {
            get {
                return ResourceManager.GetString("label_text_quantity", resourceCulture);
            }
        }
        
        internal static string label_text_search_existing_product {
            get {
                return ResourceManager.GetString("label_text_search_existing_product", resourceCulture);
            }
        }
        
        internal static string label_text_tax_rate {
            get {
                return ResourceManager.GetString("label_text_tax_rate", resourceCulture);
            }
        }
        
        internal static string status_accepted {
            get {
                return ResourceManager.GetString("status_accepted", resourceCulture);
            }
        }
        
        internal static string status_in_progress {
            get {
                return ResourceManager.GetString("status_in_progress", resourceCulture);
            }
        }
        
        internal static string status_rejected {
            get {
                return ResourceManager.GetString("status_rejected", resourceCulture);
            }
        }
        
        internal static string label_text_summary {
            get {
                return ResourceManager.GetString("label_text_summary", resourceCulture);
            }
        }
        
        internal static string alert_message_delete_quote_confirm {
            get {
                return ResourceManager.GetString("alert_message_delete_quote_confirm", resourceCulture);
            }
        }
        
        internal static string alert_title_quote {
            get {
                return ResourceManager.GetString("alert_title_quote", resourceCulture);
            }
        }
        
        internal static string page_title_edit_quote {
            get {
                return ResourceManager.GetString("page_title_edit_quote", resourceCulture);
            }
        }
        
        internal static string alert_message_intervention_undone {
            get {
                return ResourceManager.GetString("alert_message_intervention_undone", resourceCulture);
            }
        }
        
        internal static string DESCRIPTION_MOBILE_ACTIVITY_TYPE {
            get {
                return ResourceManager.GetString("DESCRIPTION_MOBILE_ACTIVITY_TYPE", resourceCulture);
            }
        }
        
        internal static string MOBILE_ACTIVITY_TYPE {
            get {
                return ResourceManager.GetString("MOBILE_ACTIVITY_TYPE", resourceCulture);
            }
        }
        
        internal static string page_title_quote_detail {
            get {
                return ResourceManager.GetString("page_title_quote_detail", resourceCulture);
            }
        }
        
        internal static string label_text_discount {
            get {
                return ResourceManager.GetString("label_text_discount", resourceCulture);
            }
        }
        
        internal static string label_text_discount_percent {
            get {
                return ResourceManager.GetString("label_text_discount_percent", resourceCulture);
            }
        }
        
        internal static string label_text_speakers {
            get {
                return ResourceManager.GetString("label_text_speakers", resourceCulture);
            }
        }
        
        internal static string label_text_add_speaker {
            get {
                return ResourceManager.GetString("label_text_add_speaker", resourceCulture);
            }
        }
        
        internal static string label_text_add_date_2 {
            get {
                return ResourceManager.GetString("label_text_add_date_2", resourceCulture);
            }
        }
        
        internal static string label_text_delete {
            get {
                return ResourceManager.GetString("label_text_delete", resourceCulture);
            }
        }
        
        internal static string label_text_edit_date_2 {
            get {
                return ResourceManager.GetString("label_text_edit_date_2", resourceCulture);
            }
        }
        
        internal static string label_text_file_name_2 {
            get {
                return ResourceManager.GetString("label_text_file_name_2", resourceCulture);
            }
        }
        
        internal static string label_text_file_size_2 {
            get {
                return ResourceManager.GetString("label_text_file_size_2", resourceCulture);
            }
        }
        
        internal static string label_text_image_height_2 {
            get {
                return ResourceManager.GetString("label_text_image_height_2", resourceCulture);
            }
        }
        
        internal static string label_text_image_width_2 {
            get {
                return ResourceManager.GetString("label_text_image_width_2", resourceCulture);
            }
        }
        
        internal static string label_text_legend_2 {
            get {
                return ResourceManager.GetString("label_text_legend_2", resourceCulture);
            }
        }
        
        internal static string label_text_save {
            get {
                return ResourceManager.GetString("label_text_save", resourceCulture);
            }
        }
        
        internal static string label_text_share {
            get {
                return ResourceManager.GetString("label_text_share", resourceCulture);
            }
        }
        
        internal static string alert_message_delete_media_confirm {
            get {
                return ResourceManager.GetString("alert_message_delete_media_confirm", resourceCulture);
            }
        }
        
        internal static string alert_title_media {
            get {
                return ResourceManager.GetString("alert_title_media", resourceCulture);
            }
        }
        
        internal static string button_text_add_an_invoice {
            get {
                return ResourceManager.GetString("button_text_add_an_invoice", resourceCulture);
            }
        }
        
        internal static string alert_message_user_already_exist {
            get {
                return ResourceManager.GetString("alert_message_user_already_exist", resourceCulture);
            }
        }
        
        internal static string alert_message_logging {
            get {
                return ResourceManager.GetString("alert_message_logging", resourceCulture);
            }
        }
        
        internal static string alert_no_internt_message {
            get {
                return ResourceManager.GetString("alert_no_internt_message", resourceCulture);
            }
        }
        
        internal static string APP_PURGE_DATA_1MONTH {
            get {
                return ResourceManager.GetString("APP_PURGE_DATA_1MONTH", resourceCulture);
            }
        }
        
        internal static string APP_PURGE_DATA_1YEAR {
            get {
                return ResourceManager.GetString("APP_PURGE_DATA_1YEAR", resourceCulture);
            }
        }
        
        internal static string APP_PURGE_DATA_3MONTHS {
            get {
                return ResourceManager.GetString("APP_PURGE_DATA_3MONTHS", resourceCulture);
            }
        }
        
        internal static string APP_PURGE_DATA_6MONTHS {
            get {
                return ResourceManager.GetString("APP_PURGE_DATA_6MONTHS", resourceCulture);
            }
        }
        
        internal static string APP_PURGE_DATA_7DAYS {
            get {
                return ResourceManager.GetString("APP_PURGE_DATA_7DAYS", resourceCulture);
            }
        }
        
        internal static string APP_PURGE_DATA_ANY {
            get {
                return ResourceManager.GetString("APP_PURGE_DATA_ANY", resourceCulture);
            }
        }
        
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        internal static string notification_new_intervention {
            get {
                return ResourceManager.GetString("notification_new_intervention", resourceCulture);
            }
        }
        
        internal static string notification_new_interventions {
            get {
                return ResourceManager.GetString("notification_new_interventions", resourceCulture);
            }
        }
        
        internal static string notification_title {
            get {
                return ResourceManager.GetString("notification_title", resourceCulture);
            }
        }
        
        internal static string label_text_or {
            get {
                return ResourceManager.GetString("label_text_or", resourceCulture);
            }
        }
        
        internal static string label_text_product_name {
            get {
                return ResourceManager.GetString("label_text_product_name", resourceCulture);
            }
        }
        
        internal static string label_text_total_ht {
            get {
                return ResourceManager.GetString("label_text_total_ht", resourceCulture);
            }
        }
        
        internal static string label_text_total_ttc {
            get {
                return ResourceManager.GetString("label_text_total_ttc", resourceCulture);
            }
        }
        
        internal static string label_text_tva {
            get {
                return ResourceManager.GetString("label_text_tva", resourceCulture);
            }
        }
        
        internal static string message_loading {
            get {
                return ResourceManager.GetString("message_loading", resourceCulture);
            }
        }
        
        internal static string notification_new_messages {
            get {
                return ResourceManager.GetString("notification_new_messages", resourceCulture);
            }
        }
        
        internal static string label_text_expiration_date {
            get {
                return ResourceManager.GetString("label_text_expiration_date", resourceCulture);
            }
        }
        
        internal static string label_text_quote_date {
            get {
                return ResourceManager.GetString("label_text_quote_date", resourceCulture);
            }
        }
        
        internal static string planning {
            get {
                return ResourceManager.GetString("planning", resourceCulture);
            }
        }
    }
}
